### ISSUE TITLE
Deploy-policyplan.ps1 seems to be removing spaces from during policy assignments

### ISSUE THREAD

**Issue by artisticcheese** [Azure/enterprise-azure-policy-as-code#129]
My assignment file is below and here is how actual assignment looks like

```
{
   // Modify Policies for required tags --- use this comment to trigger deployment
   "nodeName": "/Tags/",
   "parameters": {},
   "children": [
      {
         "nodeName": "required-and-inherit/",
         "scope": {
            "epac-dev": [
               "/providers/Microsoft.Management/managementGroups/EPAC-Dev"
            ],
            "dev-environment": [
               "/providers/Microsoft.Management/managementGroups/DevOps-mg"
            ],
            "prod-environment": [
               "/providers/Microsoft.Management/managementGroups/DevOps-mg"
            ]
         },
         "definitionEntryList": [
            {
               "initiativeName": "31fa76b5-77f6-4dda-b061-324aced74fdc",
               "assignment": {
                  "name": "tagassignment",
                  "displayName": "Require Tags Assignment",
                  "description": "Assignment for all tags"
               }
            }
         ]
      }
   ]
}
```
![image](https://user-images.githubusercontent.com/13176884/214400218-4cdf5b60-a619-4761-b5da-7e8e2e8b1ea4.png)

**Comment by techlake** [comment]
This is a bug in Az Module 9.2.x. It is fixed in Az Module. 9.3.0: see https://github.com/Azure/azure-powershell/issues/20407. Make sure your environment is updated accordingly.

**Comment by artisticcheese** [comment]
I'm using Microsoft hosted agents, they seems to be on 9.2 😥

https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#:~:text=PowerShell%20Modules-,Az%3A%209.2.0,-MarkdownPS%3A%201.9

**Comment by artisticcheese** [comment]
Solution for hosted agents to add Az update job before deployment steps for now

```
                - task: AzurePowerShell@5
                  name: updateAzVersion
                  displayName: Update Az Version
                  inputs:
                    azureSubscription: $(tenant2DeployServiceConnection)
                    pwsh: true
                    azurePowerShellVersion: LatestVersion
                    ScriptType: "InlineScript"
                    Inline: "Install-Module Az -Force; Get-InstalledModule Az;"
```
