### ISSUE TITLE
Should we convert the top level scripts to functions

### ISSUE THREAD

**Issue by techlake** [Azure/enterprise-azure-policy-as-code#182]
Question: should we do this? It would break the old-style (before the PowerShell pipeline. Fixes needed by users:
* Start using PowerShell module instead of source sync
* Dot source the scripts in a step before the actual script execution and remove the .ps1 from the invokation

**Comment by anwather** [comment]
You won't need to dot source the scripts as this happens automatically when the module is imported.

**Comment by anwather** [comment]
i.e. - this is all I have in my steps to install the module and run a command.

```
steps:
  - checkout: self
  - pwsh: |
      Install-Module EnterprisePolicyAsCode -Force
      Install-Module Az.ResourceGraph -Force
  - task: AzurePowerShell@5
    name: Plan
    displayName: Run Build
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      ScriptType: InlineScript
      azurePowerShellVersion: LatestVersion
      pwsh: true
      Inline: |
        Build-DeploymentPlans -PacEnvironmentSelector ${{ parameters.pacEnvironment }} -DefinitionsRootFolder ${{ parameters.definitionsRootFolder }} -devOpsType ado -outputFolder $env:PAC_OUTPUT_FOLDER
  - publish: "$(PAC_OUTPUT_FOLDER)"
    artifact: "policy-plan-${{ parameters.pacEnvironment }}"
    condition: and(succeeded(), or(eq(variables['Plan.deployPolicyChanges'], 'yes'), eq(variables['Plan.deployRoleChanges'], 'yes')))
```

I will put this pipeline into the starterkit in our dev environment for review.
