### ISSUE TITLE
AzDO pipeline stage name doesn't allow dashes. Default template fails

### ISSUE THREAD

**Issue by powershellpr0mpt** [Azure/enterprise-azure-policy-as-code#943]
**Describe the bug**
The default [AzDO pipeline template for remediation](https://github.com/Azure/enterprise-azure-policy-as-code/blob/c82f0e20f953856f2355f5d95a6ff1bc9b5599cd/StarterKit/Pipelines/AzureDevOps/GitHub-Flow/epac-remediation-pipeline.yml#L36C27-L36C41) will take the possible pcEnvironmentsToRemediate and loop them to create stages.
The 2 default Environments are **epac-dev** and **tenant**, however when running this you will get the error message that stage names aren't allowed to have `-` dashes in the name.

A possible fix can be to replace this line of code:

```yaml
stages:
  - ${{ each pacEnvironment in parameters.pacEnvironmentsToRemediate }}:
    - stage: Remediate${{ pacEnvironment }}
```

by this piece of code

```yaml
stages:
  - ${{ each pacEnvironment in parameters.pacEnvironmentsToRemediate }}:
    - stage: Remediate${{ replace(pacEnvironment, '-', '') }}
```

**To Reproduce**
Create a new AzDO pipeline using the template as provided above.  
Run the remediation pipeline with default environment selectors.

**Expected behavior**
When you start the AzDO pipeline using defaults (when you have both environments available) everything should just work out of the box

**Screenshots**
didn't make one

**EPAC Version**
v10.8.11
